// DO NOT EDIT — generated by: justw generate app
// Source: styles/dashboard_component.yaml
// Regenerate with: justw generate app

export interface DashboardSampleData {
  content: string;
}

export const sampleData: DashboardSampleData = {
  content: "Sample content",
};

export function populateDashboard(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
