// DO NOT EDIT — generated by: justw generate app
// Stamps every justweb.toml [mounts] container with its DDAS address.
// Source of truth: justweb.toml's [mounts] table. See justweb#69.
// Regenerate with: justw generate app

export function stampMounts(): void {
  document.querySelector("#mount-counter")?.setAttribute('data-ddas-id', "cross-target-demo:app:shell:counter"); // counter
  document.querySelector("#mount-fetch")?.setAttribute('data-ddas-id', "cross-target-demo:app:shell:fetch"); // fetch
  document.querySelector("#mount-login")?.setAttribute('data-ddas-id', "cross-target-demo:app:shell:login"); // login
}
