// DO NOT EDIT — generated by: justw generate app
// Source: styles/scaffold_component.yaml
// Regenerate with: justw generate app

export interface ScaffoldSampleData {
}

export const sampleData: ScaffoldSampleData = {
};

export function populateScaffold(root: HTMLElement): void {
}
