// DO NOT EDIT — generated by: justw generate app
// Source: styles/curation_component.yaml
// Regenerate with: justw generate app

export interface CurationSampleData {
  content: string;
}

export const sampleData: CurationSampleData = {
  content: "Sample content",
};

export function populateCuration(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
