// DO NOT EDIT — generated by: justw generate app
// Generic, lazy component map — no side effects, no static imports.
// See ADR-0008. Source of truth: *_component.yaml files
// Regenerate with: justw generate app

export const COMPONENT_REGISTRY: Record<string, () => Promise<CustomElementConstructor>> = {
  'js-cartoon': () => import('./features/cartoon/cartoon_component.gen').then(m => m.CartoonBase),
  'js-chat': () => import('./features/chat/chat_component.gen').then(m => m.ChatBase),
  'js-communication': () => import('./features/communication/communication_component.gen').then(m => m.CommunicationBase),
  'js-editor': () => import('./features/editor/editor_component.gen').then(m => m.EditorBase),
  'js-review': () => import('./features/review/review_component.gen').then(m => m.ReviewBase),
  'js-scaffold': () => import('./features/scaffold/scaffold_component.gen').then(m => m.ScaffoldBase),
  'js-socials': () => import('./features/socials/socials_component.gen').then(m => m.SocialsBase),
  'js-workspace': () => import('./features/workspace/workspace_component.gen').then(m => m.WorkspaceBase),
};
