// DO NOT EDIT — generated by: justw generate app
// Stamps every justweb.toml [mounts] container with its DDAS address.
// Source of truth: justweb.toml's [mounts] table. See justweb#69.
// Regenerate with: justw generate app

export function stampMounts(): void {
  document.querySelector("#mount-chat")?.setAttribute('data-ddas-id', "ai-code-editor:app:shell:mount-chat"); // mount-chat
  document.querySelector("#mount-editor")?.setAttribute('data-ddas-id', "ai-code-editor:app:shell:mount-editor"); // mount-editor
  document.querySelector("#mount-review")?.setAttribute('data-ddas-id', "ai-code-editor:app:shell:mount-review"); // mount-review
  document.querySelector("#mount-scaffold")?.setAttribute('data-ddas-id', "ai-code-editor:app:shell:mount-scaffold"); // mount-scaffold
  document.querySelector("#mount-workspace")?.setAttribute('data-ddas-id', "ai-code-editor:app:shell:mount-workspace"); // mount-workspace
}
