// DO NOT EDIT — generated by: justw generate app
// Routing wiring for routes.yaml — vanilla History API, no framework
// dependency. Source of truth: routes.yaml. See ADR-0006.
// Regenerate with: justw generate app

import { COMPONENT_REGISTRY } from './component-registry.gen';

interface ResolvedRoute {
  path: string;
  tag: string;
  params?: Record<string, string>;
  guard?: string;
  children?: string;
}

const ROUTES: ResolvedRoute[] = [
  {
    "path": "/home",
    "tag": "js-home",
    "children": "       <div data-part=\"content\"></div>\n"
  },
  {
    "path": "/editor",
    "tag": "js-editor",
    "children": "       <div data-part=\"gutter\"></div>\n       <pre data-part=\"highlight\"></pre>\n       <code data-part=\"highlight-code\"></code>\n       <select data-part=\"language-select\"></select>\n       <button data-part=\"review-btn\"></button>\n       <p data-part=\"sidebar-error\"></p>\n       <div data-part=\"sidebar-tree\"></div>\n       <view-status-line data-part=\"status\"></view-status-line>\n       <button data-part=\"suggest-btn\"></button>\n       <div data-part=\"surface\"></div>\n       <textarea data-part=\"textarea\"></textarea>\n"
  },
  {
    "path": "/chat",
    "tag": "js-chat",
    "children": "       <p data-part=\"context-label\"></p>\n       <p data-part=\"image-error\"></p>\n       <input data-part=\"image-input\">\n       <div data-part=\"image-preview\"></div>\n       <img data-part=\"image-thumb\">\n       <input data-part=\"message-input\">\n       <div data-part=\"messages\"></div>\n"
  },
  {
    "path": "/review",
    "tag": "js-review",
    "children": "       <div data-part=\"findings\"></div>\n       <view-image-attach data-part=\"image-attach\"></view-image-attach>\n       <view-image-picker data-part=\"image-picker\"></view-image-picker>\n       <p data-part=\"reviewed-label\"></p>\n       <button data-part=\"run-btn\"></button>\n       <p data-part=\"status\"></p>\n"
  },
  {
    "path": "/scaffold",
    "tag": "js-scaffold",
    "children": "       <pre data-part=\"code\"></pre>\n       <textarea data-part=\"description\"></textarea>\n       <div data-part=\"file-mode\"></div>\n       <input data-part=\"file-path\">\n       <button data-part=\"generate-btn\"></button>\n       <button data-part=\"generate-project-btn\"></button>\n       <view-toggle data-part=\"mode-toggle\"></view-toggle>\n       <textarea data-part=\"project-description\"></textarea>\n       <div data-part=\"project-files\"></div>\n       <p data-part=\"project-image-error\"></p>\n       <input data-part=\"project-image-input\">\n       <div data-part=\"project-image-preview\"></div>\n       <img data-part=\"project-image-thumb\">\n       <div data-part=\"project-mode\"></div>\n       <div data-part=\"project-result\"></div>\n       <div data-part=\"replace-confirm\"></div>\n       <p data-part=\"replace-message\"></p>\n       <div data-part=\"result\"></div>\n       <p data-part=\"status\"></p>\n"
  },
  {
    "path": "/connect",
    "tag": "js-connect",
    "children": "       <div data-part=\"content\"></div>\n"
  }
];

const ROOT_ID = 'app';

// The route mount container's own DDAS address (justweb#69) —
// stamped once at boot. renderCurrentRoute() never touches ROOT_ID's
// own attributes on remount, only the mounted child element, so this
// stamp is never clobbered.
const mountEl = document.getElementById(ROOT_ID);
if (mountEl) mountEl.setAttribute('data-ddas-id', 'ai-code-editor:app:shell:mount');

function matchRoute(pathname: string): { route: ResolvedRoute; captured: Record<string, string> } | null {
  const pathSegments = pathname.split('/').filter(Boolean);
  for (const route of ROUTES) {
    const routeSegments = route.path.split('/').filter(Boolean);
    if (routeSegments.length !== pathSegments.length) continue;
    const captured: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < routeSegments.length; i++) {
      const routeSegment = routeSegments[i];
      const pathSegment = pathSegments[i];
      if (routeSegment.startsWith(':')) {
        captured[routeSegment.slice(1)] = pathSegment;
      } else if (routeSegment !== pathSegment) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, captured };
  }
  return null;
}

// Full remount only — never mutate an already-connected element's
// attributes in place. See this function's doc comment above.
let mounted: Element | null = null;

// Each navigation gets a token; a lazy-loaded component that resolves
// after a *newer* navigation has already started must not clobber it —
// this can happen if an earlier route's module is slower to load than a
// later one the user already navigated to.
let renderToken = 0;

function renderCurrentRoute(): void {
  const root = document.getElementById(ROOT_ID);
  const token = ++renderToken;

  if (mounted) {
    mounted.remove();
    mounted = null;
  }
  if (!root) return;

  const match = matchRoute(window.location.pathname);
  if (!match) return;

  // Lazily load only the matched route's component — COMPONENT_REGISTRY
  // (ADR-0008) has no static imports, so nothing else the app doesn't
  // currently need gets pulled in.
  const load = COMPONENT_REGISTRY[match.route.tag];
  if (!load) return;

  load().then(() => {
    if (token !== renderToken) return; // superseded by a newer navigation

    const element = document.createElement(match.route.tag);
    if (match.route.children) {
      element.innerHTML = match.route.children;
    }
    if (match.route.params) {
      for (const [segmentName, propName] of Object.entries(match.route.params)) {
        const value = match.captured[segmentName];
        if (value !== undefined) element.setAttribute(propName, value);
      }
    }
    root.appendChild(element);
    mounted = element;
  });
}

function isSameOriginLink(url: URL): boolean {
  return url.origin === window.location.origin;
}

// Intercept same-origin <a href> clicks for client-side navigation;
// external links, modified clicks, target=_blank, and download links
// fall through to the browser's default navigation.
document.addEventListener('click', (event: MouseEvent) => {
  if (event.defaultPrevented || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
  const target = event.target as Element | null;
  const anchor = target?.closest?.('a[href]') as HTMLAnchorElement | null;
  if (!anchor || anchor.target || anchor.hasAttribute('download')) return;
  const url = new URL(anchor.href, window.location.href);
  if (!isSameOriginLink(url)) return;
  event.preventDefault();
  if (url.pathname === window.location.pathname) return;
  window.history.pushState(null, '', url.pathname);
  renderCurrentRoute();
});

window.addEventListener('popstate', () => renderCurrentRoute());

renderCurrentRoute();
