// DO NOT EDIT — generated by: justw generate app
// Routing wiring for routes.yaml — vanilla History API, no framework
// dependency. Source of truth: routes.yaml. See ADR-0006.
// Regenerate with: justw generate app

import { COMPONENT_REGISTRY } from './component-registry.gen';

interface ResolvedRoute {
  path: string;
  tag: string;
  params?: Record<string, string>;
  guard?: string;
  children?: string;
}

const ROUTES: ResolvedRoute[] = [
  {
    "path": "/editor",
    "tag": "js-editor"
  },
  {
    "path": "/chat",
    "tag": "js-chat"
  },
  {
    "path": "/review",
    "tag": "js-review"
  },
  {
    "path": "/scaffold",
    "tag": "js-scaffold"
  },
  {
    "path": "/workspace",
    "tag": "js-workspace"
  },
  {
    "path": "/communication",
    "tag": "js-communication"
  },
  {
    "path": "/socials",
    "tag": "js-socials"
  },
  {
    "path": "/cartoon",
    "tag": "js-cartoon"
  }
];

const ROOT_ID = 'app';

// The route mount container's own DDAS address (justweb#69) —
// stamped once at boot. renderCurrentRoute() never touches ROOT_ID's
// own attributes on remount, only the mounted child element, so this
// stamp is never clobbered.
const mountEl = document.getElementById(ROOT_ID);
if (mountEl) mountEl.setAttribute('data-ddas-id', 'ai-code-editor:app:shell:mount');

function matchRoute(pathname: string): { route: ResolvedRoute; captured: Record<string, string> } | null {
  const pathSegments = pathname.split('/').filter(Boolean);
  for (const route of ROUTES) {
    const routeSegments = route.path.split('/').filter(Boolean);
    if (routeSegments.length !== pathSegments.length) continue;
    const captured: Record<string, string> = {};
    let matched = true;
    for (let i = 0; i < routeSegments.length; i++) {
      const routeSegment = routeSegments[i];
      const pathSegment = pathSegments[i];
      if (routeSegment.startsWith(':')) {
        captured[routeSegment.slice(1)] = pathSegment;
      } else if (routeSegment !== pathSegment) {
        matched = false;
        break;
      }
    }
    if (matched) return { route, captured };
  }
  return null;
}

// Full remount only — never mutate an already-connected element's
// attributes in place. See this function's doc comment above.
let mounted: Element | null = null;

// Each navigation gets a token; a lazy-loaded component that resolves
// after a *newer* navigation has already started must not clobber it —
// this can happen if an earlier route's module is slower to load than a
// later one the user already navigated to.
let renderToken = 0;

function renderCurrentRoute(): void {
  const root = document.getElementById(ROOT_ID);
  const token = ++renderToken;

  if (mounted) {
    mounted.remove();
    mounted = null;
  }
  if (!root) return;

  const match = matchRoute(window.location.pathname);
  if (!match) return;

  // Lazily load only the matched route's component — COMPONENT_REGISTRY
  // (ADR-0008) has no static imports, so nothing else the app doesn't
  // currently need gets pulled in.
  const load = COMPONENT_REGISTRY[match.route.tag];
  if (!load) return;

  load().then(() => {
    if (token !== renderToken) return; // superseded by a newer navigation

    const element = document.createElement(match.route.tag);
    if (match.route.children) {
      element.innerHTML = match.route.children;
    }
    if (match.route.params) {
      for (const [segmentName, propName] of Object.entries(match.route.params)) {
        const value = match.captured[segmentName];
        if (value !== undefined) element.setAttribute(propName, value);
      }
    }
    root.appendChild(element);
    mounted = element;
  });
}

function isSameOriginLink(url: URL): boolean {
  return url.origin === window.location.origin;
}

// Intercept same-origin <a href> clicks for client-side navigation;
// external links, modified clicks, target=_blank, and download links
// fall through to the browser's default navigation.
document.addEventListener('click', (event: MouseEvent) => {
  if (event.defaultPrevented || event.button !== 0 || event.metaKey || event.ctrlKey || event.shiftKey || event.altKey) return;
  const target = event.target as Element | null;
  const anchor = target?.closest?.('a[href]') as HTMLAnchorElement | null;
  if (!anchor || anchor.target || anchor.hasAttribute('download')) return;
  const url = new URL(anchor.href, window.location.href);
  if (!isSameOriginLink(url)) return;
  event.preventDefault();
  if (url.pathname === window.location.pathname) return;
  window.history.pushState(null, '', url.pathname);
  renderCurrentRoute();
});

window.addEventListener('popstate', () => renderCurrentRoute());

renderCurrentRoute();
