// DO NOT EDIT — generated by: justw generate app
// Source: styles/review_component.yaml
// Regenerate with: justw generate app

export interface ReviewSampleData {
}

export const sampleData: ReviewSampleData = {
};

export function populateReview(root: HTMLElement): void {
}
