// DO NOT EDIT — generated by: justw generate app
// Source: styles/counter_component.yaml
// Regenerate with: justw generate app

export interface CounterSampleData {
  content: string;
}

export const sampleData: CounterSampleData = {
  content: "Sample content",
};

export function populateCounter(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
