// DO NOT EDIT — generated by: justw generate app
// Source: styles/editor_component.yaml
// Regenerate with: justw generate app

export interface EditorSampleData {
}

export const sampleData: EditorSampleData = {
};

export function populateEditor(root: HTMLElement): void {
}
