// DO NOT EDIT — generated by: justw generate app
// Source: styles/workspace_component.yaml
// Regenerate with: justw generate app

export interface WorkspaceSampleData {
  backBtn: string;
  functionList: string;
  functionListView: string;
  overviewGrid: string;
  stageTitle: string;
  subscreenView: string;
  workspaceView: string;
}

export const sampleData: WorkspaceSampleData = {
  backBtn: "Submit",
  functionList: "Sample function-list",
  functionListView: "Sample function-list-view",
  overviewGrid: "ID-001",
  stageTitle: "Sample Title",
  subscreenView: "Sample subscreen-view",
  workspaceView: "Sample workspace-view",
};

export function populateWorkspace(root: HTMLElement): void {
  const functionList = root.querySelector("[data-part='function-list']") as HTMLElement;
  if (functionList) functionList.textContent = String(sampleData.functionList);
  const functionListView = root.querySelector("[data-part='function-list-view']") as HTMLElement;
  if (functionListView) functionListView.textContent = String(sampleData.functionListView);
  const overviewGrid = root.querySelector("[data-part='overview-grid']") as HTMLElement;
  if (overviewGrid) overviewGrid.textContent = String(sampleData.overviewGrid);
  const stageTitle = root.querySelector("[data-part='stage-title']") as HTMLElement;
  if (stageTitle) stageTitle.textContent = String(sampleData.stageTitle);
  const subscreenView = root.querySelector("[data-part='subscreen-view']") as HTMLElement;
  if (subscreenView) subscreenView.textContent = String(sampleData.subscreenView);
  const workspaceView = root.querySelector("[data-part='workspace-view']") as HTMLElement;
  if (workspaceView) workspaceView.textContent = String(sampleData.workspaceView);
}
