// DO NOT EDIT — generated by: justw generate app
// Source: styles/workspace_component.yaml
// Regenerate with: justw generate app

export interface WorkspaceSampleData {
}

export const sampleData: WorkspaceSampleData = {
};

export function populateWorkspace(root: HTMLElement): void {
}
