// DO NOT EDIT — generated by: justw generate app
// Source of truth: *_component.yaml files
// Regenerate with: justw generate app

// routes.yaml is present — the router owns mounting into #app,
// lazily loading each route's component on demand.
import './routes.gen';
import { stampMounts } from './mounts.gen';
stampMounts();
