// DO NOT EDIT — generated by: justw generate app
// Generic, lazy component map — no side effects, no static imports.
// See ADR-0008. Source of truth: *_component.yaml files
// Regenerate with: justw generate app

export const COMPONENT_REGISTRY: Record<string, () => Promise<CustomElementConstructor>> = {
  'js-counter': () => import('./features/counter/counter_component.gen').then(m => m.CounterBase),
  'js-fetch-demo': () => import('./features/fetch-demo/fetch_demo_component.gen').then(m => m.FetchDemoBase),
  'js-form-demo': () => import('./features/form-demo/form_demo_component.gen').then(m => m.FormDemoBase),
};
