// DO NOT EDIT — generated by: justw generate app
// Side-effect import: registers every generated custom element.
// Source of truth: *_component.yaml files
// Regenerate with: justw generate app

import { CounterBase } from './features/counter/counter_component.gen';
import { FetchDemoBase } from './features/fetch-demo/fetch_demo_component.gen';
import { FormDemoBase } from './features/form-demo/form_demo_component.gen';

// SSR / non-browser guard. Accepts only a real CustomElementRegistry —
// rejects environments where `customElements` is missing or where a
// broken polyfill leaves `define` unimplemented.
if (typeof customElements === 'object' && customElements !== null && typeof customElements.define === 'function') {
  // Strict mode: when set, a collision throws instead of warning.
  // Opt in with `globalThis.__justwebRegistryStrict__ = true` in code
  // that runs before the registry import (e.g. early in app.ts).
  const __strict: boolean = (globalThis as { __justwebRegistryStrict__?: boolean }).__justwebRegistryStrict__ === true;
  // Tag names are emitted as string literals so this file does not depend
  // on bundlers preserving the static `tagName` member on each class.
  const __components: Array<readonly [string, CustomElementConstructor]> = [
    ['js-counter', CounterBase],
    ['js-fetch-demo', FetchDemoBase],
    ['js-form-demo', FormDemoBase],
  ];
  for (const [tag, Klass] of __components) {
    const existing = customElements.get(tag);
    if (!existing) {
      customElements.define(tag, Klass);
    } else if (existing !== Klass) {
      const msg = "[justweb] '" + tag + "' is already registered to a different class";
      if (__strict) { throw new Error(msg); }
      console.warn(msg + '; skipping registry registration');
    }
  }
}
