// DO NOT EDIT — generated by: justw generate app
// Source: styles/chat_component.yaml
// Regenerate with: justw generate app

export interface ChatSampleData {
  content: string;
}

export const sampleData: ChatSampleData = {
  content: "Sample content",
};

export function populateChat(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
