// DO NOT EDIT — generated by: justw generate app
// Source: styles/socials_component.yaml
// Regenerate with: justw generate app

export interface SocialsSampleData {
}

export const sampleData: SocialsSampleData = {
};

export function populateSocials(root: HTMLElement): void {
}
