// DO NOT EDIT — generated by: justw generate app
// Generic, lazy component map — no side effects, no static imports.
// See ADR-0008. Source of truth: *_component.yaml files
// Regenerate with: justw generate app

export const COMPONENT_REGISTRY: Record<string, () => Promise<CustomElementConstructor>> = {
  'js-chat': () => import('./features/chat/chat_component.gen').then(m => m.ChatBase),
  'js-curation': () => import('./features/curation/curation_component.gen').then(m => m.CurationBase),
  'js-dashboard': () => import('./features/dashboard/dashboard_component.gen').then(m => m.DashboardBase),
};
