// Generated by justw; do not edit.
export const JUSTWEB_MANIFEST = {
  "artifacts": [
    {
      "path": "public/dom-address-map.json",
      "sha256": "c665d6c617ed71b5eabbd05ef10f7dffa55a98f523229df928e740d5df098748"
    },
    {
      "path": "public/dom-address-map.json.sha256",
      "sha256": "5a7e8f2fa27aebfe186d39eb9b6830ae8319337ad44828d01a34ab103a609819"
    },
    {
      "path": "public/importmap.gen.json",
      "sha256": "badf3b5138c68bf66f0b12612d5ae8922abfc46d411602192f49c132ef957ec9"
    },
    {
      "path": "public/routes.gen.json",
      "sha256": "6b9d412f3fbdd92dee2da2cf20dde4220c71751d629a5ecde822c9981532ebbb"
    },
    {
      "path": "src/component-registry.gen.ts",
      "sha256": "d6e9faa17f0a982820ae1a906c302f319d573fbd65093b254e8b7d9fbebf61d6"
    },
    {
      "path": "src/features/chat/chat_browser_test.gen.ts",
      "sha256": "534d6794dc63d379db60ab238c80cfb4910d643ec1843d4c981fec42ce39b805"
    },
    {
      "path": "src/features/chat/chat_component.gen.ts",
      "sha256": "046ef957a76869b837a354574e8dfd36b7704f43444b4d8a025e9b601b208fe7"
    },
    {
      "path": "src/features/chat/chat_e2e_test.gen.ts",
      "sha256": "833cf058f27282fff93f0eb77c487c6731e1d754fcba42efa8293106c338aa7d"
    },
    {
      "path": "src/features/chat/chat_int_test.gen.ts",
      "sha256": "a2ceab8ee983ba3ac4eab1581009da96c032d06b64100bc0ca63bd404ab39354"
    },
    {
      "path": "src/features/chat/chat_mock.gen.ts",
      "sha256": "2436896fa7fe1fb306b8866477e50c4b0f3bbb1f1500d0b2ecde71b4cbc14cb6"
    },
    {
      "path": "src/features/curation/curation_browser_test.gen.ts",
      "sha256": "bc58750d817b917c60ea4810f57f89e1551c02fcc449b1d945efe8da1ca192a7"
    },
    {
      "path": "src/features/curation/curation_component.gen.ts",
      "sha256": "c7f856de5eafd3f99f93703b9abc2e472410f4898d42e54feaa07b45a8e444a6"
    },
    {
      "path": "src/features/curation/curation_e2e_test.gen.ts",
      "sha256": "7b9e6cbfeef3345d2f479899434f60c26aa92423cc8d4a7d6cf01742e7c3321b"
    },
    {
      "path": "src/features/curation/curation_int_test.gen.ts",
      "sha256": "6e025b8fbfcbbb02fffce2538994e9f3182438b991b94593a567f207cf7a254c"
    },
    {
      "path": "src/features/curation/curation_mock.gen.ts",
      "sha256": "94d398be4b48db435d672c2d7015d02f91530d969d86994d55a99199ac37c396"
    },
    {
      "path": "src/features/dashboard/dashboard_browser_test.gen.ts",
      "sha256": "0e577ded5ed33295ee71d81b99e58689f5b6b006a76863ec49267dc22a60df24"
    },
    {
      "path": "src/features/dashboard/dashboard_component.gen.ts",
      "sha256": "a2c0c04c6ec68ffe21f2d69b53053f4221fbdecdb9b49978c83ad3165eaed0af"
    },
    {
      "path": "src/features/dashboard/dashboard_e2e_test.gen.ts",
      "sha256": "4354785bf5a1c00f185606a8854841ea1f6c403c82684f9c9d4e6580eec12657"
    },
    {
      "path": "src/features/dashboard/dashboard_int_test.gen.ts",
      "sha256": "08b241a658c1d875bf7472b58a26af8c497c33e8773b18e2250a6ddc4bb914e5"
    },
    {
      "path": "src/features/dashboard/dashboard_mock.gen.ts",
      "sha256": "78b8ac5bf63e8657e86d5c70543a17c05357bf350f6586d58696f93a90d18225"
    },
    {
      "path": "src/mounts.gen.ts",
      "sha256": "066e9b3dc9bad26bd0e331774b77db95634fe4bd282f6d9eb3eec934ae5bb525"
    },
    {
      "path": "src/registry.gen.ts",
      "sha256": "81321b63f767164866d9f27dd24d0c387ff232574c90c581d9cc7caf7dd2098c"
    },
    {
      "path": "src/routes.gen.ts",
      "sha256": "97447076d1ba99a09487d5e20bab5a1fe4880646b30c54315eed1dda08f1a462"
    }
  ],
  "format": "justweb-artifact-manifest",
  "formatVersion": 1,
  "generator": {
    "name": "justw",
    "revision": "64eb51bf4d471261053f6d08dac6db5ce613abd8",
    "sourceDirty": false,
    "version": "0.1.0"
  }
} as const;
