// DO NOT EDIT — generated by: justw generate app
// Stamps every justweb.toml [mounts] container with its DDAS address.
// Source of truth: justweb.toml's [mounts] table. See justweb#69.
// Regenerate with: justw generate app

export function stampMounts(): void {
  document.querySelector("#app")?.setAttribute('data-ddas-id', "agentic-memory-demo:app:shell:chat"); // chat
  document.querySelector("#app")?.setAttribute('data-ddas-id', "agentic-memory-demo:app:shell:curation"); // curation
  document.querySelector("#app")?.setAttribute('data-ddas-id', "agentic-memory-demo:app:shell:dashboard"); // dashboard
}
