// DO NOT EDIT — generated by: justw generate app
// Source: styles/communication_component.yaml
// Regenerate with: justw generate app

export interface CommunicationSampleData {
}

export const sampleData: CommunicationSampleData = {
};

export function populateCommunication(root: HTMLElement): void {
}
