// DO NOT EDIT — generated by: justw generate app
// Source: styles/chat_component.yaml
// Regenerate with: justw generate app

export interface ChatSampleData {
}

export const sampleData: ChatSampleData = {
};

export function populateChat(root: HTMLElement): void {
}
