// DO NOT EDIT — generated by: justw generate app
// Source: styles/chat_component.yaml
// Regenerate with: justw generate app

export interface ChatSampleData {
  agentConfirm: string;
  agentConfirmMessage: string;
  agentMessages: string;
  agentStopBtn: string;
  contextLabel: string;
  imageError: string;
  imageInput: string;
  imagePreview: string;
  imageThumb: string;
  messageInput: string;
  messages: string;
  modeToggle: string;
}

export const sampleData: ChatSampleData = {
  agentConfirm: "Sample agent-confirm",
  agentConfirmMessage: "Sample agent-confirm-message",
  agentMessages: "Sample agent-messages",
  agentStopBtn: "Submit",
  contextLabel: "Sample context-label",
  imageError: "Sample image-error",
  imageInput: "Sample image-input",
  imagePreview: "Sample image-preview",
  imageThumb: "Sample image-thumb",
  messageInput: "Sample message-input",
  messages: "Sample messages",
  modeToggle: "Sample mode-toggle",
};

export function populateChat(root: HTMLElement): void {
  const agentConfirm = root.querySelector("[data-part='agent-confirm']") as HTMLElement;
  if (agentConfirm) agentConfirm.textContent = String(sampleData.agentConfirm);
  const agentConfirmMessage = root.querySelector("[data-part='agent-confirm-message']") as HTMLElement;
  if (agentConfirmMessage) agentConfirmMessage.textContent = String(sampleData.agentConfirmMessage);
  const agentMessages = root.querySelector("[data-part='agent-messages']") as HTMLElement;
  if (agentMessages) agentMessages.textContent = String(sampleData.agentMessages);
  const contextLabel = root.querySelector("[data-part='context-label']") as HTMLElement;
  if (contextLabel) contextLabel.textContent = String(sampleData.contextLabel);
  const imageError = root.querySelector("[data-part='image-error']") as HTMLElement;
  if (imageError) imageError.textContent = String(sampleData.imageError);
  const imageInput = root.querySelector("[data-part='image-input']") as HTMLInputElement;
  if (imageInput) imageInput.value = String(sampleData.imageInput);
  const imagePreview = root.querySelector("[data-part='image-preview']") as HTMLElement;
  if (imagePreview) imagePreview.textContent = String(sampleData.imagePreview);
  const imageThumb = root.querySelector("[data-part='image-thumb']") as HTMLElement;
  if (imageThumb) imageThumb.textContent = String(sampleData.imageThumb);
  const messageInput = root.querySelector("[data-part='message-input']") as HTMLInputElement;
  if (messageInput) messageInput.value = String(sampleData.messageInput);
  const messages = root.querySelector("[data-part='messages']") as HTMLElement;
  if (messages) messages.textContent = String(sampleData.messages);
  const modeToggle = root.querySelector("[data-part='mode-toggle']") as HTMLElement;
  if (modeToggle) modeToggle.textContent = String(sampleData.modeToggle);
}
