// DO NOT EDIT — generated by: justw generate app
// Source: styles/fetch-demo_component.yaml
// Regenerate with: justw generate app

export interface FetchDemoSampleData {
  content: string;
}

export const sampleData: FetchDemoSampleData = {
  content: "Sample content",
};

export function populateFetchDemo(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
