// DO NOT EDIT — generated by: justw generate app
// Source: styles/login_component.yaml
// Regenerate with: justw generate app

export interface LoginSampleData {
  content: string;
}

export const sampleData: LoginSampleData = {
  content: "Sample content",
};

export function populateLogin(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
