// DO NOT EDIT — generated by: justw generate app
// Source: styles/home_component.yaml
// Regenerate with: justw generate app

export interface HomeSampleData {
  content: string;
}

export const sampleData: HomeSampleData = {
  content: "Sample content",
};

export function populateHome(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
