// Thin app-local adapter over the real @justjs/image-connect package -
// same role core/pm_connect.ts/core/socials_connect.ts play for their
// own packages.
import { createImageConnectProvider } from "@justjs/image-connect";
import type { GeneratedImage } from "@justjs/image-connect";

export type { GeneratedImage };

export function connectOpenAi(token: string): Promise<string> {
  return createImageConnectProvider("openai", { token }).connect();
}

export function connectStability(token: string): Promise<string> {
  return createImageConnectProvider("stability", { token }).connect();
}

export function connectGemini(token: string): Promise<string> {
  return createImageConnectProvider("gemini", { token }).connect();
}

// Real, billed generation calls - each provider's own real cartoon-
// style mechanism (Stability's real style_preset field vs. OpenAI's/
// Gemini's real prompt-engineering prefix) lives inside
// @justjs/image-connect, not here.
export function generateOpenAiCartoon(token: string, prompt: string): Promise<GeneratedImage> {
  return createImageConnectProvider("openai", { token }).generate(prompt);
}

export function generateStabilityCartoon(token: string, prompt: string): Promise<GeneratedImage> {
  return createImageConnectProvider("stability", { token }).generate(prompt);
}

export function generateGeminiCartoon(token: string, prompt: string): Promise<GeneratedImage> {
  return createImageConnectProvider("gemini", { token }).generate(prompt);
}

// The real inverse of core/images.ts's own parseDataUrl() - builds a
// real "data:<mimeType>;base64,<data>" URL string from a generated
// image's own {mimeType, base64} shape, reusing the same naming
// convention that module already established, so an `<img src="...">`
// can display the real generated bytes directly - no upload, no
// separate fetch, the base64 the provider returned is the whole image.
export function buildImageDataUrl(image: GeneratedImage): string {
  return `data:${image.mimeType};base64,${image.base64}`;
}
