// DO NOT EDIT — generated by: justw generate app
// Source: styles/cartoon_component.yaml
// Regenerate with: justw generate app

export interface CartoonSampleData {
}

export const sampleData: CartoonSampleData = {
};

export function populateCartoon(root: HTMLElement): void {
}
