// DO NOT EDIT — generated by: justw generate app
// Source: styles/form-demo_component.yaml
// Regenerate with: justw generate app

export interface FormDemoSampleData {
  content: string;
}

export const sampleData: FormDemoSampleData = {
  content: "Sample content",
};

export function populateFormDemo(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
