import { describe, it, expect } from "bun:test"
import { generateCodeWithStrategies } from "../core/codegen"
import type { JustJSConfig } from "../api/config"

const mockStrategies = new Map([
  ["@justjs/aop-security-oauth", "/vendor/security-oauth.js"],
  ["@justjs/aop-security-saml", "/vendor/security-saml.js"],
  ["@justjs/aop-observability-datadog", "/vendor/observability-datadog.js"],
  ["@justjs/aop-observability-prometheus", "/vendor/observability-prometheus.js"],
  ["@justjs/aop-flags-launchdarkly", "/vendor/flags-launchdarkly.js"],
  ["@justjs/aop-analytics-segment", "/vendor/analytics-segment.js"],
  ["@justjs/aop-theming-runtime", "/vendor/theming-runtime.js"],
  ["@justjs/aop-i18n-intl", "/vendor/i18n-intl.js"],
])

describe("codegen", () => {
  describe("generateCodeWithStrategies", () => {
    it("test_generate_empty_config_produces_minimal_boot", () => {
      const config: JustJSConfig = {}
      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain("justjs.boot")
      expect(output.imports).toHaveLength(0)
    })

    it("test_generate_single_strategy_produces_import", () => {
      const config: JustJSConfig = {
        security: {
          strategy: "oauth",
          on_routes: ["/dashboard"],
        },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain('import "@justjs/aop-security-oauth"')
      expect(output.imports).toContain('import "@justjs/aop-security-oauth"')
      expect(output.code).toContain("security")
    })

    it("test_generate_multiple_strategies_produces_all_imports", () => {
      const config: JustJSConfig = {
        security: { strategy: "oauth", on_routes: ["/"] },
        observability: { strategy: "datadog", all: true },
        flags: { strategy: "launchdarkly" },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.imports).toHaveLength(3)
      expect(output.code).toContain("security")
      expect(output.code).toContain("observability")
      expect(output.code).toContain("flags")
    })

    it("test_generate_config_with_routes_included", () => {
      const config: JustJSConfig = {
        security: {
          strategy: "oauth",
          on_routes: ["/dashboard", "/account"],
        },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain('"/dashboard"')
      expect(output.code).toContain('"/account"')
      expect(output.code).toContain('"on"')
    })

    it("test_generate_nests_every_concern_under_a_single_aspects_key_matching_BootConfig_aspects (justjs#60)", () => {
      // @justjs/application's BootConfig only reads aspect declarations from
      // a nested `aspects: Record<string, AspectConfig>` map - a flat
      // top-level `security`/`observability`/etc. key is silently ignored by
      // both BootValidator and boot()'s resolve/weave loop (confirmed:
      // application/api/boot.ts's BootConfig has no top-level fields for
      // these at all, only `[key: string]: unknown`). This test evaluates
      // the generated output for real, not just string-matching, so a
      // regression back to flat top-level keys would actually fail this.
      const config: JustJSConfig = {
        security: {
          strategy: "oauth",
          on_routes: ["/dashboard", "/account"],
          on_components: ["x-user-menu"],
          except_routes: ["/login"],
        },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)
      const bootConfigMatch = output.code.match(/\.\.\.(\{[\s\S]*?\}),\n\s*\.\.\.config/)
      expect(bootConfigMatch).not.toBeNull()
      const bootConfig = JSON.parse(bootConfigMatch![1]!)

      expect(bootConfig.security).toBeUndefined()
      expect(bootConfig.aspects).toBeDefined()
      expect(bootConfig.aspects.security).toEqual({
        strategy: "oauth",
        routes: { on: ["/dashboard", "/account"], except: ["/login"] },
        components: { on: ["x-user-menu"] },
      })
    })

    it("test_generate_code_marks_as_autogenerated", () => {
      const config: JustJSConfig = {
        security: { strategy: "oauth" },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain("Auto-generated")
      expect(output.code).toContain("do not edit")
    })

    it("test_generate_code_imports_application_layer", () => {
      const config: JustJSConfig = {
        security: { strategy: "oauth" },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain('import { justjs } from "@justjs/application"')
      expect(output.code).toContain('import type { BootConfig } from "@justjs/application"')
      expect(output.code).toContain('export async function boot(config?: Partial<BootConfig>)')
      expect(output.code).toContain('justjs.boot(')
    })

    it("test_generate_unknown_strategy_throws_error", () => {
      const config: JustJSConfig = {
        security: { strategy: "unknown" },
      }

      expect(() =>
        generateCodeWithStrategies(config, mockStrategies)
      ).toThrow()
    })
  })
})
