import { describe, it, expect } from "bun:test"
import { generateCodeWithStrategies } from "../core/codegen"
import type { JustJSConfig } from "../api/config"

const mockStrategies = new Map([
  ["@justjs/aop-security-oauth", "/vendor/security-oauth.js"],
  ["@justjs/aop-security-saml", "/vendor/security-saml.js"],
  ["@justjs/aop-observability-datadog", "/vendor/observability-datadog.js"],
  ["@justjs/aop-observability-prometheus", "/vendor/observability-prometheus.js"],
  ["@justjs/aop-flags-launchdarkly", "/vendor/flags-launchdarkly.js"],
  ["@justjs/aop-analytics-segment", "/vendor/analytics-segment.js"],
  ["@justjs/aop-theming-runtime", "/vendor/theming-runtime.js"],
  ["@justjs/aop-i18n-intl", "/vendor/i18n-intl.js"],
])

describe("codegen", () => {
  describe("generateCodeWithStrategies", () => {
    it("test_generate_empty_config_produces_minimal_boot", () => {
      const config: JustJSConfig = {}
      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain("JustJS.boot")
      expect(output.imports).toHaveLength(0)
    })

    it("test_generate_single_strategy_produces_import", () => {
      const config: JustJSConfig = {
        security: {
          strategy: "oauth",
          on: ["/dashboard"],
        },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain('import "@justjs/aop-security-oauth"')
      expect(output.imports).toContain('import "@justjs/aop-security-oauth"')
      expect(output.code).toContain("security")
    })

    it("test_generate_multiple_strategies_produces_all_imports", () => {
      const config: JustJSConfig = {
        security: { strategy: "oauth", on: ["/"] },
        observability: { strategy: "datadog", all: true },
        flags: { strategy: "launchdarkly" },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.imports).toHaveLength(3)
      expect(output.code).toContain("security")
      expect(output.code).toContain("observability")
      expect(output.code).toContain("flags")
    })

    it("test_generate_config_with_routes_included", () => {
      const config: JustJSConfig = {
        security: {
          strategy: "oauth",
          on: ["/dashboard", "/account"],
        },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain('"/dashboard"')
      expect(output.code).toContain('"/account"')
      expect(output.code).toContain('"on"')
    })

    it("test_generate_code_marks_as_autogenerated", () => {
      const config: JustJSConfig = {
        security: { strategy: "oauth" },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain("Auto-generated")
      expect(output.code).toContain("do not edit")
    })

    it("test_generate_code_imports_application_layer", () => {
      const config: JustJSConfig = {
        security: { strategy: "oauth" },
      }

      const output = generateCodeWithStrategies(config, mockStrategies)

      expect(output.code).toContain('import { JustJS } from "@justjs/application"')
      expect(output.code).toContain('export async function boot(config)')
    })

    it("test_generate_unknown_strategy_throws_error", () => {
      const config: JustJSConfig = {
        security: { strategy: "unknown" },
      }

      expect(() =>
        generateCodeWithStrategies(config, mockStrategies)
      ).toThrow()
    })
  })
})
