// DO NOT EDIT — generated by: justw generate app
// Source: styles/fetch_component.yaml
// Regenerate with: justw generate app

export interface FetchSampleData {
  content: string;
}

export const sampleData: FetchSampleData = {
  content: "Sample content",
};

export function populateFetch(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
