// DO NOT EDIT — generated by: justw generate app
// Source: styles/connect_component.yaml
// Regenerate with: justw generate app

export interface ConnectSampleData {
  content: string;
}

export const sampleData: ConnectSampleData = {
  content: "Sample content",
};

export function populateConnect(root: HTMLElement): void {
  const content = root.querySelector("[data-part='content']") as HTMLElement;
  if (content) content.textContent = String(sampleData.content);
}
